services:

  _defaults:
    public: false
    autowire: true

  OxidEsales\FreeShippingCoupons\Infrastructure\VoucherFactoryInterface:
    class: OxidEsales\FreeShippingCoupons\Infrastructure\FactoryInterface

  OxidEsales\FreeShippingCoupons\Service\FreeShippingVoucherServiceInterface:
    class: OxidEsales\FreeShippingCoupons\Service\FreeShippingVoucherService